import React, {useEffect, useRef, useState} from 'react';

const sources={'zhipu+rule-v1':'智谱建议＋规则复核','rule-v1':'规则自动通过','deepseek+rule-v1':'AI建议＋规则复核','human-single':'人工逐单通过','human-batch':'人工批量通过'};
const samples=[['stock','合成：请核实这款咖啡的库存，页面显示缺货。'],['supply','合成：请核实这款饮料的在途和到货计划。'],['refund','合成：退货已收，退款进度需要财务核查。']];
export default function Collaboration({api,run,busy,conversations,session}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[actor,setActor]=useState('客服');
 const [cid,setCid]=useState(''),[category,setCategory]=useState('stock'),[selected,setSelected]=useState({});
 const [preview,setPreview]=useState(null),[attempted,setAttempted]=useState(false),[receipt,setReceipt]=useState(null);const mounted=useRef(true);
 async function load(){const result=await api('/collaboration/state');if(mounted.current)setData(result);}
 useEffect(()=>{mounted.current=true;load().catch(e=>setError(e.message));return()=>{mounted.current=false;};},[conversations]);
 function change(fn,message){return run(async()=>{setError('');try{await fn();}finally{await load();}},message);}
 if(!data)return <section className="card pad">{error||'正在读取协作工单…'}</section>;
 const loggedIn=data.auth==='server-verified-login',effectiveActor=loggedIn?data.role:actor,actorPayload=loggedIn?{}:{actor:effectiveActor},chosen=conversations.find(c=>c.id===cid);
 async function create(conversation,kind){await api('/collaboration/tickets',{...actorPayload,conversation_id:conversation.id,expected_revision:conversation.revision,category:kind});}
 function sample(kind,question){change(async()=>{const response=await api('/messages',{question,synthetic_or_redacted:true,event_id:crypto.randomUUID()});await create({id:response.conversation_id,revision:1},kind);},'合成工单已保存，审批及派发状态由后端记录');}
 function previewBatch(){setPreview({...actorPayload,items:Object.entries(selected).map(([id,expected_version])=>({id,expected_version})),request_id:crypto.randomUUID()});setAttempted(false);setReceipt(null);}
 function submitBatch(){setAttempted(true);change(async()=>{const response=await api('/collaboration/batch-approve',preview);setReceipt(response);setPreview(null);setSelected({});},'批次已返回逐单结果；请查看成功及跳过项');}
 return <><div className="heading"><div><h1>协作工单</h1><p className="muted">人工批量审批，或按规则自动派给运营、供应链、仓储物流、财务和质量。</p></div></div>
 <div className="note warn">{loggedIn?`单店本地登录：当前为 ${session.user_ref}（${effectiveActor}），角色由后端会话验证。`:'单店本地演示：角色切换仅模拟操作职责。'} 工单真实保存于本地数据库；派发仅进入本地部门队列，未通知企业群。</div>{error&&<div role="alert" className="note risk">{error}</div>}
 <section className="card pad"><div className="grid2">{loggedIn?<div><strong>当前登录角色</strong><p>{session.user_ref} · {effectiveActor}</p></div>:<label>本地演示角色<select aria-label="本地演示角色" disabled={busy||!!preview} value={actor} onChange={e=>{setActor(e.target.value);setSelected({});}}>{data.roles.map(r=><option key={r}>{r}</option>)}</select></label>}<label>审批模式（主管设置）<select aria-label="审批模式" disabled={busy||effectiveActor!=='主管'||!!preview} value={data.policy.mode} onChange={e=>change(()=>api('/collaboration/policy',{...actorPayload,expected_version:data.policy.version,mode:e.target.value},'PUT'),'审批模式已保存；仅影响之后提交的工单')}><option value="manual">人工审批：可逐单或批量</option><option value="rules">规则内自动审批并派发</option><option value="ai" disabled={!data.model_configured}>AI辅助自动审批（需要模型配置）</option></select></label></div><p className="small muted">规则版本 {data.policy.version}。自动审批仅适用于白名单内的状态核实；AI判断后仍需后端复核。不允许自动退款、付款、采购或调拨。</p></section>
 {effectiveActor==='客服'&&<section className="card pad" style={{marginTop:16}}><h2>客服提交工单</h2><div className="grid2"><label>选择已有合成咨询<select aria-label="选择工单咨询" disabled={busy} value={cid} onChange={e=>setCid(e.target.value)}><option value="">请选择</option>{conversations.map(c=><option key={c.id} value={c.id}>{c.messages[0].text.slice(0,45)} · v{c.revision}</option>)}</select></label><label>问题分类<select aria-label="工单分类" disabled={busy} value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(data.categories).map(([key,c])=><option key={key} value={key}>{c.label}</option>)}</select></label></div><button className="primary" disabled={busy||!chosen} onClick={()=>change(()=>create(chosen,category),'工单已保存；重复建单返回已有记录')}>确认提交协作工单</button><div className="actions">{samples.map(([kind,question])=><button key={kind} disabled={busy} onClick={()=>sample(kind,question)}>新建合成：{data.categories[kind].label}</button>)}</div></section>}
 <section className="card pad" style={{marginTop:16}}><div className="heading"><h2>审批与部门队列 · {data.tickets.length} 项</h2><button disabled={busy} onClick={()=>change(()=>Promise.resolve(),'已刷新协作工单')}>刷新工单</button></div><p className="small muted">每批最多 50 项。请检查工单内容和所选版本后确认。</p><div className="actions"><button disabled={busy||effectiveActor!=='主管'||!!preview||!data.tickets.some(t=>t.batch_eligible)} onClick={()=>setSelected(Object.fromEntries(data.tickets.filter(t=>t.batch_eligible).slice(0,50).map(t=>[t.id,t.version])))}>选择当前可批量项</button><button disabled={busy||effectiveActor!=='主管'||!!preview||!Object.keys(selected).length} onClick={previewBatch}>预览批量审批（{Object.keys(selected).length}）</button></div>{preview&&<div className="note warn"><strong>将审核 {preview.items.length} 项，逐单复核所选版本</strong>{preview.items.map(i=><p key={i.id}>{data.tickets.find(t=>t.id===i.id)?.summary||'工单'} · {i.id.slice(0,8)} · 所选 v{i.expected_version}</p>)}<p>风险、已处理或版本变化项会跳过并返回原因；成功项进入各自的本地部门队列。</p><div className="actions"><button className="primary" disabled={busy||effectiveActor!=='主管'} onClick={submitBatch}>{attempted?'重试同一批次并查询结果':'确认批量通过'}</button><button disabled={busy||attempted} onClick={()=>setPreview(null)}>取消预览</button></div></div>}{receipt&&<div className="note" role="status"><strong>批次结果：成功 {receipt.results.filter(r=>r.ok).length}，跳过 {receipt.results.filter(r=>!r.ok).length}</strong>{receipt.results.map(r=><p key={r.id}>{r.id.slice(0,8)}：{r.ok?'已通过，进入本地部门队列':r.reason}</p>)}</div>}</section>
 {!data.tickets.length&&<section className="card empty" style={{marginTop:16}}>暂无协作工单。可先创建一个合成场景。</section>}{data.tickets.map(t=><WorkTicket key={t.id+':'+t.version} ticket={t} actor={effectiveActor} busy={busy} categories={data.categories} selected={selected[t.id]!==undefined} locked={!!preview} onSelect={checked=>setSelected(s=>{const next={...s};if(checked&&Object.keys(next).length<50)next[t.id]=t.version;else if(!checked)delete next[t.id];return next;})} action={body=>change(()=>api('/collaboration/tickets/'+encodeURIComponent(t.id)+'/actions',{...actorPayload,expected_version:t.version,...body}),'工单动作已保存；不代表真实资金或采购执行')} conversation={conversations.find(c=>c.id===t.conversation_id)}/>)}</>;
}
function WorkTicket({ticket:t,actor,busy,categories,selected,locked,onSelect,action,conversation}){
 const [note,setNote]=useState(''),[category,setCategory]=useState(t.category),stale=conversation&&conversation.revision!==t.message_revision,resubmit=t.state==='待补充'||t.state==='待分诊'||(stale&&t.state!=='已结案');
 return <section className="card pad" style={{marginTop:16}}><div className="heading"><div><h2>{t.summary} <span className="pill warn">{t.state}</span></h2><p className="small muted">{t.id.slice(0,8)} · 工单 v{t.version} · {t.department||'尚未派给执行部门'} · {sources[t.approval_source]||'尚未批准'}</p></div>{actor==='主管'&&t.state==='待审批'&&<label><input aria-label={'选择工单 '+t.id.slice(0,8)} type="checkbox" disabled={busy||locked} checked={selected} onChange={e=>onSelect(e.target.checked)}/>纳入批次</label>}</div><p>{conversation?.messages.at(-1)?.text}</p><p className="small muted">{t.eligibility_reason}</p>{t.review_reason&&<p className="small muted">最近审核记录：{t.review_reason}</p>}{stale&&<div className="note warn">咨询已更新，原审批不可继续使用；请客服补充重提。</div>}{t.dispatch_status==='local_queue_only'&&<p className="small muted">本地部门队列已记录，企业群通知未发送。</p>}{t.resolution&&<div className="note">部门反馈：{t.resolution}</div>}{t.state!=='已结案'&&<><label>合成处理依据 / 驳回或补充说明<textarea aria-label={'处理说明 '+t.id.slice(0,8)} value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="仅填写合成或脱敏内容。核查完成不代表退款或采购完成。"/></label>{resubmit&&actor==='客服'&&<label>重提分类<select aria-label={'重提分类 '+t.id.slice(0,8)} value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(categories).map(([key,c])=><option key={key} value={key}>{c.label}</option>)}</select></label>}<div className="actions">{actor==='主管'&&t.state==='待审批'&&<><button className="primary" disabled={busy||stale} onClick={()=>action({action:'approve'})}>逐单通过并派发</button><button disabled={busy||!note.trim()} onClick={()=>action({action:'reject',note})}>驳回补充</button></>}{actor==='客服'&&resubmit&&<button disabled={busy||!note.trim()} onClick={()=>action({action:'resubmit',note,category})}>补充并重新提交审核</button>}{actor===t.department&&t.state==='待接单'&&<button disabled={busy||stale} className="primary" onClick={()=>action({action:'accept'})}>部门接单</button>}{actor===t.department&&t.state==='处理中'&&<button disabled={busy||stale||!note.trim()} className="primary" onClick={()=>action({action:'feedback',note})}>回传处理结果</button>}{actor==='客服'&&t.state==='待客服确认'&&<><button disabled={busy||stale||!note.trim()} onClick={()=>action({action:'return',note})}>退回部门补充</button><button className="primary" disabled={busy||stale||!note.trim()} onClick={()=>action({action:'close',note})}>确认本次核查完成</button></>}</div></>}<details style={{marginTop:12}}><summary>查看处理记录（{t.history.length}）</summary>{t.history.map(e=><p className="small muted" key={e.id}>{new Date(e.at).toLocaleString()} · {e.actor} · {e.action}{e.note?' · '+e.note:''}</p>)}</details></section>;
}
